name: Test Summary Action
description: A GitHub Action to summarize JUnit tests in a Gradle project

branding:
  icon: award
  color: green

runs:
  using: 'docker'
  image: 'docker://ghcr.io/jeantessier/test-summary-action:latest'
